export type BuildingKey =
  | "Bangunan Gorong - Gorong"
  | "Bangunan Terjun"
  | "Jembatan Saluran"
  | "Talang"
  | "Bangunan Pelimpah"
  | "Bangunan Pembuang"
  | "Bangunan Pembilas"
  | "Bangunan Penahan dan Pengaman"
  | "Syphone"
  | "Terowongan"
  | "Cross Drain"
  | "Pelimpah Samping"
  | "Drain Inlet"
  | "Got Miring";

export const BUILDINGS: BuildingKey[] = [
  "Bangunan Gorong - Gorong",
  "Bangunan Terjun",
  "Jembatan Saluran",
  "Talang",
  "Bangunan Pelimpah",
  "Bangunan Pembuang",
  "Bangunan Pembilas",
  "Bangunan Penahan dan Pengaman",
  "Syphone",
  "Terowongan",
  "Cross Drain",
  "Pelimpah Samping",
  "Drain Inlet",
  "Got Miring",
];

// Data Rincian Pekerjaan Sesuai PDF REVISI TERBARU
export const TASKS: Record<BuildingKey, string[]> = {
  "Bangunan Gorong - Gorong": [
    "Pembersihan Sampah",
    "Galian Lumpur sedalam <= 1 m",
    "Galian Tanah Biasa sedalam < 1 m",
    "Timbunan Tanah atau Urugan Tanah Kembali",
    "Pemadatan Tanah",
    "Timbunan Pasir sebagai Bahan Pengisi",
    "Pemadatan Pasir sebagai Bahan Pengisi",
    "Mengangkut 1 m3 Hasil Galian (3-5 m)",
    "Mengangkut 1 m3 Hasil Galian (10 m)",
    "Mengangkut 1 m3 Hasil Galian (30 m)",
    "Bongkar Pasangan Batu dan Pembersihan Batu",
    "Pasangan Batu 1 PC: 4 PS",
    "Plesteran Tebal 1 cm",
    "Siaran",
    "Acian",
    "Beton Lantai Kerja",
    "Beton Mutu FC 14,5 MPa (K-175)",
    "Beton Mutu FC 19,3 MPa (K-225)",
    "Beton Mutu FC 21,7 MPa (K-250)",
    "Beton Bertulang T=8 cm",
    "Bongkar Beton",
  ],
  "Bangunan Terjun": [
    "Pembersihan Sampah",
    "Galian Lumpur sedalam <= 1 m",
    "Galian Tanah Biasa sedalam < 1 m",
    "Timbunan Tanah atau Urugan Tanah Kembali",
    "Pemadatan Tanah",
    "Mengangkut Hasil Galian (3 m)",
    "Mengangkut Hasil Galian (10 m)",
    "Mengangkut Hasil Galian (30 m)",
    "Bongkar Pasangan Batu",
    "Pasangan Batu",
    "Pasangan Bronjong Pabrikasi",
    "Pasangan Batu Kosong",
    "Plesteran",
    "Siaran",
    "Acian",
    "Beton Lantai Kerja",
    "Beton K-175",
    "Beton K-225",
    "Beton K-250",
    "Beton Bertulang",
    "Bongkar Beton",
    "Pemasangan Kistdam",
  ],
  "Jembatan Saluran": [
    "Pembersihan Sampah",
    "Galian Tanah Biasa sedalam < 1 m",
    "Timbunan Tanah atau Urugan Tanah Kembali",
    "Pemadatan Tanah",
    "Mengangkut Hasil Galian (3 m)",
    "Mengangkut Hasil Galian (10 m)",
    "Mengangkut Hasil Galian (30 m)",
    "Bongkar Beton",
    "Beton Lantai Kerja",
    "Beton K-175",
    "Beton K-225",
    "Beton K-250",
    "Beton Bertulang",
    "Plesteran",
    "Siaran",
    "Acian",
    "Pengecatan baru",
    "Pengecatan lama",
  ],
  Talang: [
    "Pembersihan sampah",
    "Galian Lumpur sedalam <= 1 m",
    "Galian Tanah Biasa sedalam < 1 m",
    "Timbunan Tanah atau Urugan Tanah Kembali",
    "Pemadatan Tanah",
    "Mengangkut Hasil Galian (3 m)",
    "Mengangkut Hasil Galian (10 m)",
    "Mengangkut Hasil Galian (30 m)",
    "Bongkar Beton",
    "Pasangan batu",
    "Plesteran",
    "Siaran",
    "Acian",
    "Beton lantai kerja",
    "Beton K-175",
    "Beton K-225",
    "Beton K-250",
  ],
  "Bangunan Pelimpah": [
    "Pembersihan Sampah",
    "Galian Lumpur sedalam < 1 m",
    "Galian Tanah Biasa sedalam < 1 m",
    "Timbunan Tanah atau Urugan Tanah Kembali",
    "Pemadatan Tanah",
    "Mengangkut Hasil Galian (3 m)",
    "Mengangkut Hasil Galian (10 m)",
    "Mengangkut Hasil Galian (30 m)",
    "Bongkar Pasangan Batu",
    "Pasangan batu",
    "Pasangan Bronjong Pabrikasi",
    "Pasangan Batu Kosong",
    "Plesteran",
    "Siaran",
    "Acian",
    "Beton lantai kerja",
    "Beton K-175",
    "Beton K-225",
    "Beton K-250",
    "Bongkaran Beton",
    "Pemasangan kistdam",
  ],
  "Bangunan Pembuang": [
    "Pembersihan sampah",
    "Galian Lumpur sedalam < 1m",
    "Galian Tanah Biasa sedalam < 1 m",
    "Mengangkut Hasil Galian (3 m)",
    "Mengangkut Hasil Galian (10 m)",
    "Mengangkut Hasil Galian (30 m)",
    "Bongkar Batu",
    "Pasangan Batu",
    "Plesteran",
    "Siaran",
    "Acian",
    "Beton lantai kerja",
    "Beton K-175",
    "Beton K-225",
    "Beton K-250",
    "Bongkaran Beton",
    "Pekerjaan Pintu B=2,5 m H=2,0 m",
    "Seluruh pilihan Pintu Angkat",
    "Seluruh pilihan Pintu Sorong",
    "Seluruh pilihan Pintu Sorong Ganda",
    "Seluruh pilihan Pintu Romyn",
    "Pelumasan Pintu Angkat",
    "Pelumasan Pintu Sorong",
    "Pengecatan lama",
    "Pengecatan baru",
  ],
  "Bangunan Pembilas": [
    "Pembersihan sampah",
    "Galian Lumpur sedalam < 1m",
    "Galian Tanah Biasa sedalam < 1 m",
    "Mengangkut Hasil Galian (3 m)",
    "Mengangkut Hasil Galian (10 m)",
    "Mengangkut Hasil Galian (30 m)",
    "Bongkar Batu",
    "Pasangan Batu",
    "Plesteran",
    "Siaran",
    "Acian",
    "Beton lantai kerja",
    "Beton K-175",
    "Beton K-225",
    "Beton K-250",
    "Bongkaran Beton",
    "Pekerjaan Pintu B=2,5 m H=2,0 m",
    "Seluruh pilihan Pintu Angkat",
    "Seluruh pilihan Pintu Sorong",
    "Seluruh pilihan Pintu Sorong Ganda",
    "Seluruh pilihan Pintu Romyn",
    "Pelumasan Pintu Angkat",
    "Pelumasan Pintu Sorong",
    "Pengecatan lama",
    "Pengecatan baru",
  ],
  "Bangunan Penahan dan Pengaman": [
    "Pembersihan Sampah",
    "Galian Lumpur sedalam < 1m",
    "Galian Tanah Biasa sedalam < 1 m",
    "Timbunan Tanah atau Urugan Tanah Kembali",
    "Pemadatan Tanah",
    "Mengangkut Hasil Galian (3 m)",
    "Mengangkut Hasil Galian (10 m)",
    "Mengangkut Hasil Galian (30 m)",
    "Bongkar Pasangan Batu",
    "Pasangan batu",
    "Pasangan Bronjong Pabrikasi",
    "Pasangan Batu Kosong",
    "Plesteran",
    "Siaran",
    "Acian",
    "Beton lantai kerja",
    "Beton K-175",
    "Beton K-225",
    "Beton K-250",
    "Bongkaran Beton",
    "Pemasangan kistdam",
  ],
  Syphone: [
    "Pembersihan Sampah",
    "Galian Lumpur sedalam < 1m",
    "Galian Tanah Biasa sedalam < 1 m",
    "Timbunan Tanah atau Urugan Tanah Kembali",
    "Pemadatan Tanah",
    "Mengangkut Hasil Galian (3 m)",
    "Mengangkut Hasil Galian (10 m)",
    "Mengangkut Hasil Galian (30 m)",
    "Bongkar Pasangan Batu",
    "Pasangan batu",
    "Plesteran",
    "Siaran",
    "Acian",
    "Beton lantai kerja",
    "Beton K-175",
    "Beton K-225",
    "Beton K-250",
    "Bongkaran Beton",
    "Pengecatan baru",
    "Pengecatan lama",
  ],
  Terowongan: [
    "Pembersihan Sampah",
    "Galian Lumpur sedalam < 1m",
    "Mengangkut Hasil Galian (3 m)",
    "Mengangkut Hasil Galian (10 m)",
    "Mengangkut Hasil Galian (30 m)",
    "Bongkar Beton",
    "Pasangan batu",
    "Plesteran",
    "Siaran",
    "Acian",
    "Beton bertulang",
    "Beton K-175",
    "Beton K-225",
    "Beton K-250",
  ],
  "Cross Drain": [
    "Pembersihan Sampah",
    "Galian Lumpur sedalam < 1m",
    "Galian Tanah Biasa sedalam < 1 m",
    "Timbunan Tanah atau Urugan Tanah Kembali",
    "Pemadatan Tanah",
    "Mengangkut Hasil Galian (3 m)",
    "Mengangkut Hasil Galian (10 m)",
    "Mengangkut Hasil Galian (30 m)",
    "Bongkar Pasangan Batu",
    "Pasangan batu",
    "Plesteran",
    "Siaran",
    "Acian",
    "Beton lantai kerja",
    "Beton K-175",
    "Beton K-225",
    "Beton K-250",
    "Bongkaran Bertulang",
  ],
  "Pelimpah Samping": [
    "Pembersihan Sampah",
    "Galian Lumpur sedalam < 1m",
    "Mengangkut Hasil Galian (3 m)",
    "Mengangkut Hasil Galian (10 m)",
    "Mengangkut Hasil Galian (30 m)",
    "Bongkar pasangan batu",
    "Pasangan batu",
    "Pasangan bronjong pabrikasi",
    "Pasangan batu kosong",
    "Plesteran",
    "Siaran",
    "Acian",
    "Beton bertulang",
    "Beton K-175",
    "Beton K-225",
    "Beton K-250",
    "Pemasangan kistdam",
  ],
  "Drain Inlet": [
    "Pembersihan Sampah",
    "Galian Lumpur sedalam < 1m",
    "Galian Tanah Biasa sedalam < 1 m",
    "Timbunan Tanah atau Urugan Tanah Kembali",
    "Pemadatan Tanah",
    "Mengangkut Hasil Galian (3 m)",
    "Mengangkut Hasil Galian (10 m)",
    "Mengangkut Hasil Galian (30 m)",
    "Bongkar Pasangan Batu",
    "Pasangan batu",
    "Plesteran",
    "Siaran",
    "Acian",
    "Beton lantai kerja",
    "Beton K-175",
    "Beton K-225",
    "Beton K-250",
  ],
  "Got Miring": [
    "Pembersihan Sampah",
    "Galian Lumpur sedalam < 1m",
    "Galian Tanah Biasa sedalam < 1 m",
    "Timbunan Tanah atau Urugan Tanah Kembali",
    "Pemadatan Tanah",
    "Mengangkut Hasil Galian (3 m)",
    "Mengangkut Hasil Galian (10 m)",
    "Mengangkut Hasil Galian (30 m)",
    "Bongkar Pasangan Batu",
    "Pasangan batu",
    "Plesteran",
    "Siaran",
    "Acian",
    "Beton lantai kerja",
    "Beton K-175",
    "Beton K-225",
    "Beton K-250",
    "Beton bertulang",
  ],
};

// Fungsi Pencari Harga Otomatis dari AHSP (Paten)
export const getAhspPrice = (taskName: string): number => {
  const name = taskName.toLowerCase().trim();
  
  if (name.includes("galian tanah biasa")) return 87500;
  if (name.includes("galian lumpur")) return 129000;
  if (name.includes("timbunan tanah") || name.includes("urugan tanah")) return 51280;
  if (name === "pemadatan tanah" || name.includes("pemadatan tanah")) return 89930;
  if (name.includes("timbunan pasir")) return 303660;
  if (name.includes("pemadatan pasir")) return 39980;
  
  if (name.includes("mengangkut") && (name.includes("3 m") || name.includes("3-5 m")) && !name.includes("30")) return 36400;
  if (name.includes("mengangkut") && name.includes("10 m")) return 39920;
  if (name.includes("mengangkut") && name.includes("30 m")) return 52250;
  
  if (name.includes("pasangan batu 1 pc") || name === "pasangan batu") return 1364460;
  if (name.includes("siaran")) return 89180;
  if (name.includes("acian")) return 57100;
  
  return 0; 
};

export const formatIDR = (n: number) =>
  new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0,
  }).format(isFinite(n) ? n : 0);